apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-application-properties-secret
  namespace: ecommerce
type: Opaque
data:
  MARIADB_HOST: "192.168.19.25"
  MARIADB_NAME: "full-stack-ecommerce"
  MARIADB_PASSWORD: "StrongPa55WorD"
  MARIADB_PORT: "3306"
  MARIADB_USER: "ecommerceapp"